# Generated by Django 4.2.11 on 2024-05-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_timestap',
            new_name='created_timestamp',
        ),
    ]
