# Generated by Django 4.2.11 on 2024-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['order'], 'verbose_name': 'Зображення для каруселі', 'verbose_name_plural': 'Зображення для каруселі'},
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='carousel/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер в черзі '),
        ),
    ]
