# Generated by Django 4.2.11 on 2024-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options_alter_color_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Зображення в розмірі 1920 X 1080'),
        ),
    ]
